"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

export type SavedTotoBet = { id:string;savedAt:string;asOf:string;mode:string;numbers:number[];budget:number;researchScore:number;suggestedDeployment:number;uncommitted:number;evidence:string;placed?:boolean;actualStake?:number;actualPrize?:number;ticketNote?:string };
export type PublishedTotoDraw={drawNo:string;drawDate:string;main:number[];additional:number|null};
const STORAGE_KEY="lottery-intel:toto-saved-bets:v1";
function readSaved():SavedTotoBet[]{if(typeof window==="undefined")return[];try{return JSON.parse(localStorage.getItem(STORAGE_KEY)??"[]")as SavedTotoBet[]}catch{return[]}}
function persist(items:SavedTotoBet[]){localStorage.setItem(STORAGE_KEY,JSON.stringify(items))}
const money=(n:number)=>`S$${n.toFixed(2)}`;
const modeLabel=(mode:string)=>({match2:"Match 2",match3:"Match 3",match4:"Match 4",standard:"Standard",system:"System"}[mode]??mode.toUpperCase());

export function SaveTotoBetButton({bet}:{bet:Omit<SavedTotoBet,"id"|"savedAt">}){const[saved,setSaved]=useState(false);function save(){const current=readSaved(),item:SavedTotoBet={...bet,id:crypto.randomUUID(),savedAt:new Date().toISOString(),placed:false};persist([item,...current].slice(0,100));setSaved(true)}return <div><button type="button" onClick={save} disabled={saved}>{saved?"Saved to My TOTO History":"Save this research"}</button> <Link href="/toto/history">View my history →</Link></div>}

function targetDraw(item:SavedTotoBet,draws:PublishedTotoDraw[]){return [...draws].filter(d=>d.drawDate>item.asOf).sort((a,b)=>a.drawDate.localeCompare(b.drawDate))[0]??null}
function grade(item:SavedTotoBet,draws:PublishedTotoDraw[]){const draw=targetDraw(item,draws);if(!draw)return null;const hits=item.numbers.filter(n=>draw.main.includes(n)).length,add=draw.additional!==null&&item.numbers.includes(draw.additional);return{draw,hits,add,label:`${hits} main matched${add?" + Additional":""}`}}

type StrategySummary={mode:string;placed:number;graded:number;hits2plus:number;staked:number;prizes:number;net:number;roi:number};
export function TotoSavedHistory({publishedDraws}:{publishedDraws:PublishedTotoDraw[]}){
  const[items,setItems]=useState<SavedTotoBet[]>([]);useEffect(()=>setItems(readSaved()),[]);
  function update(id:string,patch:Partial<SavedTotoBet>){const next=items.map(i=>i.id===id?{...i,...patch}:i);persist(next);setItems(next)}
  function remove(id:string){const next=items.filter(i=>i.id!==id);persist(next);setItems(next)}
  const summary=useMemo(()=>{const placed=items.filter(i=>i.placed),graded=placed.map(i=>({i,g:grade(i,publishedDraws)})).filter(x=>x.g).sort((a,b)=>(b.g?.draw.drawDate??"").localeCompare(a.g?.draw.drawDate??"")),wins=graded.filter(x=>(x.g?.hits??0)>=2).length;let dry=0;for(const x of graded){if((x.g?.hits??0)>=2)break;dry++}const staked=placed.reduce((s,i)=>s+(Number(i.actualStake)||0),0),prizes=placed.reduce((s,i)=>s+(Number(i.actualPrize)||0),0),net=prizes-staked,roi=staked>0?100*net/staked:0;return{saved:items.length,placed:placed.length,graded:graded.length,wins,dry,staked,prizes,net,roi}},[items,publishedDraws]);
  const strategies=useMemo(()=>{const modes=[...new Set(items.filter(i=>i.placed).map(i=>i.mode))];return modes.map(mode=>{const subset=items.filter(i=>i.placed&&i.mode===mode),graded=subset.filter(i=>grade(i,publishedDraws)),staked=subset.reduce((s,i)=>s+(Number(i.actualStake)||0),0),prizes=subset.reduce((s,i)=>s+(Number(i.actualPrize)||0),0),net=prizes-staked;return{mode,placed:subset.length,graded:graded.length,hits2plus:graded.filter(i=>(grade(i,publishedDraws)?.hits??0)>=2).length,staked,prizes,net,roi:staked>0?100*net/staked:0}as StrategySummary}).sort((a,b)=>b.roi-a.roi)},[items,publishedDraws]);
  const latestDraw=[...publishedDraws].sort((a,b)=>b.drawDate.localeCompare(a.drawDate))[0]??null;
  if(!items.length)return <p className="state">No saved TOTO research yet. Analyse a bet and save it to start building your personal record.</p>;
  return <><section className="ranking-method"><span className="eyebrow">Personal scoreboard</span><h2>{summary.graded} graded · {summary.wins} with 2+ main matches</h2><p>Research saved: {summary.saved} · Marked placed: {summary.placed}</p><p><strong>Actual staked: {money(summary.staked)} · Prizes recorded: {money(summary.prizes)} · Net: {summary.net>=0?"+":""}{money(summary.net)} · ROI: {summary.roi.toFixed(1)}%</strong></p>{summary.dry>=5&&<p><strong>Budget Guard:</strong> {summary.dry} consecutive graded placed entries without 2+ main matches. Consider taking a break rather than increasing stake.</p>}{latestDraw&&<p>Latest published draw {latestDraw.drawNo} · {latestDraw.drawDate}: <strong>{latestDraw.main.map(n=>String(n).padStart(2,"0")).join(" · ")}</strong>{latestDraw.additional!==null?` + Additional ${String(latestDraw.additional).padStart(2,"0")}`:""}</p>}</section>
  {!!strategies.length&&<section className="ranking-method"><span className="eyebrow">Strategy performance</span><h2>Which approach has worked best for you?</h2><div className="stats-preview">{strategies.map(s=><article key={s.mode}><strong>{modeLabel(s.mode)}</strong><span>{s.graded} graded · {s.hits2plus} with 2+ matches</span><span>{money(s.staked)} staked · {money(s.prizes)} prizes</span><small>Net {s.net>=0?"+":""}{money(s.net)} · ROI {s.roi.toFixed(1)}%</small></article>)}</div><p className="coverage-note">Personal performance is descriptive history, not evidence that a strategy will repeat its past result.</p></section>}
  <div className="recent-grid">{items.map(item=>{const g=grade(item,publishedDraws),stake=Number(item.actualStake)||0,prize=Number(item.actualPrize)||0;return <article className="recent-card" key={item.id}><div><h3>{modeLabel(item.mode)} · {item.researchScore}/100</h3><p>Saved {new Date(item.savedAt).toLocaleString("en-SG")}</p></div><p><strong>{item.numbers.map(n=>String(n).padStart(2,"0")).join(" · ")}</strong></p><p>Budget S${item.budget} · AI suggested S${item.suggestedDeployment} · Keep S${item.uncommitted}</p><p>{item.evidence} · research data through {item.asOf}</p><label><input type="checkbox" checked={!!item.placed} onChange={e=>update(item.id,{placed:e.target.checked})}/> I actually placed this bet</label>{item.placed&&<div className="lucky-form"><label><span>Actual amount spent (S$)</span><input type="number" min="0" step="0.50" value={item.actualStake??""} onChange={e=>update(item.id,{actualStake:Math.max(0,Number(e.target.value)||0)})}/></label><label><span>Ticket / bet note</span><input type="text" placeholder="e.g. 5 Match 3 selections × $5" value={item.ticketNote??""} onChange={e=>update(item.id,{ticketNote:e.target.value})}/></label>{g&&<label><span>Actual prize received (S$)</span><input type="number" min="0" step="0.50" value={item.actualPrize??""} onChange={e=>update(item.id,{actualPrize:Math.max(0,Number(e.target.value)||0)})}/></label>}</div>}{g?<p><strong>Graded against Draw {g.draw.drawNo} · {g.draw.drawDate}: {g.label}</strong><br/>{item.placed?`Actual record: ${money(stake)} staked · ${money(prize)} prize · net ${prize-stake>=0?"+":""}${money(prize-stake)}.`:"Research-only: not counted financially unless you confirm it was placed."}</p>:<p>Waiting for the next published draw after this research date.</p>}<button type="button" onClick={()=>remove(item.id)}>Remove</button></article>})}</div>
  <aside className="rankings-warning"><strong>Prize entry:</strong> enter the actual prize paid on the ticket. Lottery Intel automatically identifies the correct subsequent draw and matched numbers, but does not invent variable cash payouts.</aside></>;
}
