import { createServerClient } from "@/lib/supabase/server";

export type TotoResearchMode = "match2" | "match3" | "match4" | "standard" | "system";
export type RelationshipScore = { numbers:number[]; score:number; countPrimary:number; countSecondary?:number; rankPrimary:number; rankSecondary?:number; percentile:number };
export type TotoAlternative = { replace:number; with:number; scoreBefore:number; scoreAfter:number; improvement:number; resultingNumbers:number[] };
export type TotoResearchAnalysis = { asOf:string; mode:TotoResearchMode; researchScore:number; evidence:"Experimental"|"Moderate evidence"|"High variance"; strongest:RelationshipScore[]; weakest:RelationshipScore[]; numberScores:Array<{number:number;appearances365:number;appearances90:number;score:number}>; alternatives:TotoAlternative[]; suggestedDeployment:number; explanation:string };
type TotoResultRow={draw_id:string;draw_date:string;number_kind:"main"|"additional";winning_number:number}; type DrawSet={date:string;numbers:number[]};
function combinations(v:number[],s:number){const o:number[][]=[];const w=(i:number,p:number[])=>{if(p.length===s){o.push([...p]);return}for(let x=i;x<=v.length-(s-p.length);x++){p.push(v[x]);w(x+1,p);p.pop()}};w(0,[]);return o}
const keyOf=(n:number[])=>n.join("-"); const daysBefore=(date:string,days:number)=>{const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()-days);return d.toISOString().slice(0,10)};
function relationshipCounts(draws:DrawSet[],size:number,cutoff:string){const m=new Map<string,number>();for(const d of draws){if(d.date<cutoff)continue;for(const c of combinations(d.numbers,size)){const k=keyOf(c);m.set(k,(m.get(k)??0)+1)}}return m}
function rankMap(c:Map<string,number>){const s=[...c.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));const r=new Map<string,number>();s.forEach(([k],i)=>r.set(k,i+1));return{ranks:r,total:Math.max(s.length,1)}}
const pctFromRank=(r:number,t:number)=>Math.max(0,Math.min(100,Math.round(100*(1-(r-1)/Math.max(t,1)))));
function scoreCombo(combo:number[],primary:Map<string,number>,pRank:ReturnType<typeof rankMap>,secondary?:Map<string,number>,sRank?:ReturnType<typeof rankMap>):RelationshipScore{const k=keyOf([...combo].sort((a,b)=>a-b)),cp=primary.get(k)??0,rp=pRank.ranks.get(k)??pRank.total+1,p1=pctFromRank(rp,pRank.total+1);if(!secondary||!sRank)return{numbers:[...combo].sort((a,b)=>a-b),score:p1,countPrimary:cp,rankPrimary:rp,percentile:p1};const cs=secondary.get(k)??0,rs=sRank.ranks.get(k)??sRank.total+1,p2=pctFromRank(rs,sRank.total+1),st=Math.max(0,100-Math.abs(p1-p2));return{numbers:[...combo].sort((a,b)=>a-b),score:Math.round(.4*p1+.4*p2+.2*st),countPrimary:cp,countSecondary:cs,rankPrimary:rp,rankSecondary:rs,percentile:Math.round((p1+p2)/2)}}
function setScore(nums:number[],size:number,primary:Map<string,number>,pRank:ReturnType<typeof rankMap>,secondary?:Map<string,number>,sRank?:ReturnType<typeof rankMap>){const r=combinations([...nums].sort((a,b)=>a-b),size).map(c=>scoreCombo(c,primary,pRank,secondary,sRank)).sort((a,b)=>b.score-a.score);return r.length?r.slice(0,Math.min(5,r.length)).reduce((s,x)=>s+x.score,0)/Math.min(5,r.length):0}

export async function analyseTotoNumbers(numbers:number[],mode:TotoResearchMode,budget:number):Promise<{data:TotoResearchAnalysis|null;error:string|null}>{try{const client=createServerClient();if(!client)return{data:null,error:"Supabase public credentials are unavailable."};const result=await client.schema("api_public").from("published_toto_results").select("draw_id,draw_date,number_kind,winning_number").eq("number_kind","main").order("draw_date",{ascending:false}).limit(2000);if(result.error)return{data:null,error:result.error.message};const rows=(result.data??[])as TotoResultRow[];if(!rows.length)return{data:null,error:"No published TOTO history is available."};const asOf=rows[0].draw_date,grouped=new Map<string,DrawSet>();for(const row of rows){const c=grouped.get(row.draw_id)??{date:row.draw_date,numbers:[]};c.numbers.push(row.winning_number);grouped.set(row.draw_id,c)}const draws=[...grouped.values()].map(d=>({...d,numbers:[...new Set(d.numbers)].sort((a,b)=>a-b)}));const c365=daysBefore(asOf,365),c210=daysBefore(asOf,210),c180=daysBefore(asOf,180),c90=daysBefore(asOf,90),f365=new Map<number,number>(),f90=new Map<number,number>();for(const d of draws)for(const n of d.numbers){if(d.date>=c365)f365.set(n,(f365.get(n)??0)+1);if(d.date>=c90)f90.set(n,(f90.get(n)??0)+1)}const m365=Math.max(...f365.values(),1),m90=Math.max(...f90.values(),1);const numberScores=numbers.map(number=>{const a=f365.get(number)??0,b=f90.get(number)??0;return{number,appearances365:a,appearances90:b,score:Math.round(100*(.6*a/m365+.4*b/m90))}}).sort((a,b)=>b.score-a.score);
const size=mode==="match2"?2:mode==="match3"?3:mode==="match4"?4:1;let relationships:RelationshipScore[]=[],alternatives:TotoAlternative[]=[],evidence:TotoResearchAnalysis["evidence"]="Moderate evidence",explanation="Individual-number frequency is supporting context only; larger System pools are not automatically treated as better.";if(size>1){const primary=relationshipCounts(draws,size,mode==="match2"?c365:c180),pRank=rankMap(primary),secondary=mode==="match3"?relationshipCounts(draws,size,c210):undefined,sRank=secondary?rankMap(secondary):undefined;relationships=combinations([...numbers].sort((a,b)=>a-b),size).map(c=>scoreCombo(c,primary,pRank,secondary,sRank)).sort((a,b)=>b.score-a.score);const before=setScore(numbers,size,primary,pRank,secondary,sRank);const candidatePool=Array.from({length:49},(_,i)=>i+1).filter(n=>!numbers.includes(n));for(const replace of numbers){for(const withN of candidatePool){const resulting=[...numbers.filter(n=>n!==replace),withN].sort((a,b)=>a-b),after=setScore(resulting,size,primary,pRank,secondary,sRank);if(after>before)alternatives.push({replace,with:withN,scoreBefore:Math.round(before),scoreAfter:Math.round(after),improvement:Math.round(after-before),resultingNumbers:resulting})}}alternatives.sort((a,b)=>b.improvement-a.improvement||b.scoreAfter-a.scoreAfter);const seen=new Set<string>();alternatives=alternatives.filter(a=>{const k=a.resultingNumbers.join("-");if(seen.has(k))return false;seen.add(k);return true}).slice(0,5);evidence=mode==="match3"?"Experimental":mode==="match4"?"High variance":"Moderate evidence";explanation=mode==="match2"?"Match 2 prioritises exact pair co-occurrence over the last 365 days.":mode==="match3"?"Match 3 uses consensus between exact triple relationships over 180 and 210 days, rewarding stability across both windows.":"Match 4 uses exact 180-day quadruple relationships and is labelled high variance because historical wins were rare."}
const component=relationships.length?relationships.slice(0,Math.min(5,relationships.length)).reduce((s,r)=>s+r.score,0)/Math.min(5,relationships.length):numberScores.reduce((s,n)=>s+n.score,0)/Math.max(numberScores.length,1),researchScore=Math.round(component),base=mode==="match2"?Math.min(budget,5):mode==="match3"?Math.min(budget,25):mode==="match4"?Math.min(budget,10):Math.min(budget,mode==="system"?84:20),suggestedDeployment=researchScore<45?Math.min(base,Math.ceil(budget*.2)):base;return{data:{asOf,mode,researchScore,evidence,strongest:relationships.slice(0,5),weakest:[...relationships].sort((a,b)=>a.score-b.score).slice(0,3),numberScores,alternatives,suggestedDeployment,explanation},error:null}}catch(error){return{data:null,error:error instanceof Error?error.message:"Unable to analyse TOTO numbers."}}}
